GET http://localhost:8080/usuarios

###
GET http://localhost:8080/mascotas?perdido=false&animal=Perro

###
GET http://localhost:8080/mascotas/Ciro

###
POST http://localhost:8080/mascotas
content-type: application/json

{
    "name": "Bola de nieve",
    "edad": 4
}